import { Metadata } from 'next';
export const metadata: Metadata = {
  title: { absolute: '무시할 수 없는 블로그' },
  //description: 'Generated by Next.js',
};
// export const meta: Metadata = {
//   title: {
//     absolute: 'Blog',
//     //description: 'Blog page',
//   },
// };

export default function Blog() {
  return <h1>My blog</h1>;
}
